import type { Metadata } from "next";
import "./globals.css";
import HeaderComponent from "@/components/header/header.component";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeaderComponent />
        {children}
        {process.env.NEXT_PUBLIC_APP_VERSION ?? "nv"}
      </body>
    </html>
  );
}
