"use client";

import Link from "next/link";
import Image from "next/image";
import { useLocale } from "next-intl";
import ShowcaseHero from "@/components/pages/about/showcase/showcase-hero.component";
import { useL } from "@/components/pages/about/showcase/showcase-l10n";
import {
  ExploreCard,
  ExploreCardCount,
  ExploreCardCta,
  ExploreCardTitle,
  ExploreGrid,
  ShowcaseSection,
  ShowcaseSectionSub,
  ShowcaseSectionTitle,
  TechBlock,
  TechChip,
  TechChips,
  TechGroup,
  TechGroupTitle,
} from "@/components/pages/about/showcase/showcase-section.styled";
import {
  AboutPageContainer,
  AboutPageSectionBlock,
  AboutPageSectionImage,
  AboutPageSectionText,
} from "@/components/pages/about/about-page-layout/about-page-layout.styled";
import { showcaseStats, showcaseCrystalsObtained } from "@/data/showcase";
import { tutorialBlocks } from "@/data/about";

export default function Home() {
  const locale = useLocale();
  const L = useL();

  const cards = [
    {
      href: "/catalog",
      title: L("Catalog", "Каталог"),
      count: `${showcaseStats.totalPenguins} ${L("penguins", "пингвинов")}`,
    },
    {
      href: "/market",
      title: L("Market", "Рынок"),
      count: `${showcaseStats.onMarket} ${L("offers", "лотов")}`,
    },
    {
      href: "/evolution",
      title: L("Evolution", "Эволюция"),
      count: L("visual demo", "визуал-демо"),
    },
    {
      href: "/expeditions",
      title: L("Expeditions", "Экспедиции"),
      count: `${showcaseStats.totalExpeditions} ${L("runs", "ходок")}`,
    },
    {
      href: "/events",
      title: L("Events", "Ивенты"),
      count: `${showcaseStats.totalEvents} ${L("events", "ивентов")}`,
    },
    {
      href: "/crystals",
      title: L("Crystals", "Кристаллы"),
      count: `${showcaseCrystalsObtained} ${L("obtained", "получено")}`,
    },
  ];

  const techGroups = [
    {
      label: L("Frontend", "Фронтенд"),
      items: [
        "Next.js 16 (App Router)",
        "React",
        "TypeScript",
        "styled-components",
        "next-intl",
        "Jotai",
      ],
    },
    {
      label: L("Data & Auth", "Данные · авторизация"),
      items: ["Firebase Auth", "Cloud Firestore", "firebase-admin"],
    },
    {
      label: L("AI generation", "AI-генерация"),
      items: ["Replicate · SDXL ControlNet", "OpenAI GPT"],
    },
    {
      label: L("Media & storage", "Медиа · хранилище"),
      items: ["Supabase Storage → GitHub + jsDelivr CDN", "sharp · WebP"],
    },
    {
      label: L("Hosting", "Хостинг"),
      items: ["Vercel", "Serverless API routes"],
    },
  ];

  return (
    <>
      <ShowcaseHero />

      <ShowcaseSection>
        <ShowcaseSectionTitle>{L("Explore", "Разделы")}</ShowcaseSectionTitle>
        <ExploreGrid>
          {cards.map((c) => (
            <Link key={c.href} href={c.href} style={{ textDecoration: "none" }}>
              <ExploreCard>
                <ExploreCardTitle>{c.title}</ExploreCardTitle>
                <ExploreCardCount>{c.count}</ExploreCardCount>
                <ExploreCardCta className="ce-cta">
                  {L("Open", "Открыть")} <span className="arrow">→</span>
                </ExploreCardCta>
              </ExploreCard>
            </Link>
          ))}
        </ExploreGrid>
      </ShowcaseSection>

      <ShowcaseSection>
        <ShowcaseSectionTitle>
          {L("How it worked", "Как это работало")}
        </ShowcaseSectionTitle>
        <AboutPageContainer>
          {tutorialBlocks.map((section, i) => (
            <AboutPageSectionBlock key={i} reverse={i % 2 !== 0}>
              <AboutPageSectionImage>
                <Image
                  width={200}
                  height={250}
                  src={`/tutorial/${section.img}.webp`}
                  alt={`Section ${i + 1}`}
                />
              </AboutPageSectionImage>
              <AboutPageSectionText>
                {section[locale as "ru" | "en"]}
              </AboutPageSectionText>
            </AboutPageSectionBlock>
          ))}
        </AboutPageContainer>
      </ShowcaseSection>

      <ShowcaseSection>
        <ShowcaseSectionTitle>
          {L("Under the hood", "Под капотом")}
        </ShowcaseSectionTitle>
        <ShowcaseSectionSub>
          {L(
            "Penguins were generated by an AI model on demand, converted to WebP, stored on a CDN and indexed in a realtime database. Fully serverless.",
            "Пингвины генерировались AI-моделью по запросу, конвертировались в WebP, складывались в CDN и индексировались в realtime-базе. Полностью serverless."
          )}
        </ShowcaseSectionSub>
        <TechBlock>
          {techGroups.map((g) => (
            <TechGroup key={g.label}>
              <TechGroupTitle>{g.label}</TechGroupTitle>
              <TechChips>
                {g.items.map((item) => (
                  <TechChip key={item}>{item}</TechChip>
                ))}
              </TechChips>
            </TechGroup>
          ))}
        </TechBlock>
      </ShowcaseSection>
    </>
  );
}
